# Form implementation generated from reading ui file 'test_window.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets
from PyQt6.QtWidgets import QMainWindow


class Ui_MainWindow(QMainWindow):
    def __init__(self):
        super().__init__()
        self._setupUi()

    def _setupUi(self):
        self.setObjectName("MainWindow")
        self.resize(454, 321)
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.statementTable = QtWidgets.QTableWidget(self.centralwidget)
        self.statementTable.setDragDropOverwriteMode(False)
        self.statementTable.setObjectName("statementTable")
        self.statementTable.setColumnCount(2)
        self.statementTable.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.statementTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.statementTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.statementTable.setHorizontalHeaderItem(1, item)
        self.statementTable.horizontalHeader().setStretchLastSection(True)
        self.statementTable.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.statementTable)
        self.getButton = QtWidgets.QPushButton(self.centralwidget)
        self.getButton.setObjectName("getButton")
        self.verticalLayout.addWidget(self.getButton)
        self.setCentralWidget(self.centralwidget)

        self._retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def _retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.statementTable.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.statementTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "勘定科目"))
        item = self.statementTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "金額"))
        self.getButton.setText(_translate("MainWindow", "取得"))
