# Form implementation generated from reading ui file 'UserManager.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets


class Ui_UserManager(QtWidgets.QWidget):
    def __init__(self):
        super().__init__()
        self.setupUi()

    def setupUi(self):
        self.setObjectName("UserManager")
        self.resize(465, 645)
        self.verticalLayout = QtWidgets.QVBoxLayout(self)
        self.verticalLayout.setObjectName("verticalLayout")
        self.dateEdit = QtWidgets.QDateEdit(self)
        self.dateEdit.setObjectName("dateEdit")
        self.verticalLayout.addWidget(self.dateEdit)
        self.calendarWidget = QtWidgets.QCalendarWidget(self)
        self.calendarWidget.setObjectName("calendarWidget")
        self.verticalLayout.addWidget(self.calendarWidget)
        self.tableWidget_userList = QtWidgets.QTableWidget(self)
        self.tableWidget_userList.setObjectName("tableWidget_userList")
        self.tableWidget_userList.setColumnCount(2)
        self.tableWidget_userList.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_userList.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_userList.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_userList.setHorizontalHeaderItem(1, item)
        self.tableWidget_userList.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_userList.horizontalHeader().setMinimumSectionSize(24)
        self.tableWidget_userList.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_userList.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.tableWidget_userList)
        self._horizontalLayout = QtWidgets.QHBoxLayout()
        self._horizontalLayout.setObjectName("_horizontalLayout")
        self.lineEdit_userName = QtWidgets.QLineEdit(self)
        self.lineEdit_userName.setObjectName("lineEdit_userName")
        self._horizontalLayout.addWidget(self.lineEdit_userName)
        self.pushButton_searchByUserName = QtWidgets.QPushButton(self)
        self.pushButton_searchByUserName.setObjectName("pushButton_searchByUserName")
        self._horizontalLayout.addWidget(self.pushButton_searchByUserName)
        self.pushButton_getAllUsers = QtWidgets.QPushButton(self)
        self.pushButton_getAllUsers.setObjectName("pushButton_getAllUsers")
        self._horizontalLayout.addWidget(self.pushButton_getAllUsers)
        self.verticalLayout.addLayout(self._horizontalLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit_newUserName = QtWidgets.QLineEdit(self)
        self.lineEdit_newUserName.setObjectName("lineEdit_newUserName")
        self.horizontalLayout.addWidget(self.lineEdit_newUserName)
        self.spinBox_age = QtWidgets.QSpinBox(self)
        self.spinBox_age.setObjectName("spinBox_age")
        self.horizontalLayout.addWidget(self.spinBox_age)
        self.pushButton_addUser = QtWidgets.QPushButton(self)
        self.pushButton_addUser.setObjectName("pushButton_addUser")
        self.horizontalLayout.addWidget(self.pushButton_addUser)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("UserManager", "ユーザー管理システム"))
        item = self.tableWidget_userList.verticalHeaderItem(0)
        item.setText(_translate("UserManager", "1"))
        item = self.tableWidget_userList.horizontalHeaderItem(0)
        item.setText(_translate("UserManager", "名前"))
        item = self.tableWidget_userList.horizontalHeaderItem(1)
        item.setText(_translate("UserManager", "年齢"))
        self.pushButton_searchByUserName.setText(_translate("UserManager", "名前で検索"))
        self.pushButton_getAllUsers.setText(_translate("UserManager", "すべて取得"))
        self.pushButton_addUser.setText(_translate("UserManager", "登録"))
