name: chomenou-unit-test-python
on:
  push:
    branches:
      - main
      - feature/**
  workflow_dispatch:

jobs:
  python-unit-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -r requirements.txt

      - name: Run Unit test
        run: python -m unittest -v tests/test*.py
